### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by justinsanda** [derickongeri/shoreline_extractor#11]
ValueError: data must be a string, ee.FeatureCollection, ee.Feature, or ee.Geometry. 
Traceback (most recent call last):
  File "C:\Users/LENOVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\shoreline_extractor\shoreline_extractor.py", line 264, in process
    extract_SAR_Shoreline(self.dlg)
  File "C:\Users/LENOVO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\shoreline_extractor\SAR_Shoreline_Extractor.py", line 82, in extract_SAR_Shoreline
    grid = geemap.fishnet(roi, h_interval=0.05, v_interval=0.05, delta=1)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python39\site-packages\geemap\common.py", line 7969, in fishnet
    raise ValueError(
ValueError: data must be a string, ee.FeatureCollection, ee.Feature, or ee.Geometry.

**Comment by JCAELA** [comment]
![error](https://github.com/derickongeri/shoreline_extractor/assets/100201026/d956b14d-0bf4-43c1-bd21-38ebabd714bc)
I have the same issue.
